### ISSUE TITLE
Cache maintenance worker thread causing periodic slow mem reads when FLAG_NOCACHE is used

### ISSUE THREAD

**Issue by uberhalit** [ufrisk/MemProcFS#113] opened 2022-08-07 19:30 UTC
The worker thread [VmmProcCacheUpdaterThread](https://github.com/ufrisk/MemProcFS/blob/master/vmm/vmmproc.c#L178) from `/vmm/vmmproc.c` seems to cause huge slowdowns on memory reads through FPGAs in a periodic manner when `FLAG_NOCACHE` is provided. I wrote a minimum example here: https://gist.github.com/uberhalit/da9b5fd700fe06eba7a20adcc65607ce
This is the output: 
![grafik](https://user-images.githubusercontent.com/19159295/183307820-207ca73a-caa2-4114-807e-cb23eb417df7.png)

Normally a read takes <1ms but about every 10-15 seconds a single 8 byte read will take 50-150ms. 

Providing `-norefresh` will disable the cache maintenance worker as documented [here](https://github.com/ufrisk/MemProcFS/blob/master/vmm/vmmdll_core.c#L282) and the slow reads will vanish.

**Comment by ufrisk** [comment] 2022-08-08 06:38
I'd say this is more or less expected behavior even if 60ms looks to be on the high side of things. Issue is that there needs to be some refreshes of certain things (process listings, page tables etc.) so they don't start to drift too much. Also the access to the FPGA is serialized (single-threaded) so your NOCACHE read request will just have to wait until the refresh is finished.

You may disable refreshes manually as you mention, but then it's a good idea to force periodic refreshes manually. (VMMDLL_OPT_REFRESH_FREQ_FAST / VMMDLL_OPT_REFRESH_FREQ_MEDIUM / VMMDLL_OPT_REFRESH_FREQ_SLOW).

---

1) Since it looks to me that its a bit on the high side of things have you verified with "pcileech dump" or MemProcFS that you are indeed getting USB3 speeds (100MB+/s) or rather USB2 speeds (40MB/s).

2) Have you verified that the base of the explorer is indeed in physical memory? Can you do a phys2virt translation on it? In rare cases it may be moved into compressed memory by WIndows and that will slow things down a lot - especially with the NO_CACHE flag and after a refresh has been initiated.

3) Also please let me know if you feel there is an increased slowdown with the new API. I don't see how that could be, and I don't think there is, but I made some substantial changes so I you never know 100%.

**Comment by uberhalit** [comment] 2022-08-16 22:27
Ah thanks for your quick response. I had some time to play around more. How'd I periodically trigger a refresh manually? I am assuming I'd have to first set and then after 1 second reset the OPT_REFRESH_FREQ_MEDIUM back to 0? There are quiet a few flags available for a call to `vmm.ConfigSet()`:
```cs
OPT_CONFIG_IS_REFRESH_ENABLED
OPT_CONFIG_READCACHE_TICKS
OPT_REFRESH_ALL
OPT_REFRESH_FREQ_FAST
OPT_REFRESH_FREQ_MEDIUM
OPT_REFRESH_FREQ_SLOW
OPT_REFRESH_READ
```

**Comment by ufrisk** [comment] 2022-08-17 22:40
you may disable the refresh either by option or command-line option at startup. if disabled it's good to perform refreshes manually.

write 1 to the option to perform the action. no need to "reset" the action.

VMMDLL_OPT_REFRESH_FREQ_FAST = some quick refresh options, including partial process refresh
VMMDLL_OPT_REFRESH_FREQ_MEDIUM = total process refresh
VMMDLL_OPT_REFRESH_FREQ_SLOW = pretty much all refreshes (can sometimes be a bit slow).

**Comment by uberhalit** [comment] 2022-08-18 15:57
Figured that out already. How often should one trigger SLOW & MEDIUM? Or is it enought to call FAST every few seconds and SLOW maybe once every few minutes?

**Comment by ufrisk** [comment] 2022-08-19 16:00
default is 5s/15s/5m for fast/medium/slow.

**Comment by ufrisk** [comment] 2022-08-21 20:17
I hope this question is answered. I close this issue now. Please let me know if you should have any remaining questions around this.

**Closed by ufrisk** 2022-08-21 20:17 UTC

**Comment by dolodi** [comment] 2024-03-11 10:55
> default is 5s/15s/5m for fast/medium/slow.

How do i set the period for them?

VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_FAST, 1);
VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_MEDIUM, 1);
VMMDLL_ConfigSet(hVMM, VMMDLL_OPT_REFRESH_FREQ_SLOW, 1);

if this just makes them refresh one time right ? I just used vmdlll configSet with them but it wasnt refreshing at all.
