### ISSUE TITLE
Some Windows 7 memory images cannot analyze dst ip and dst port.

### ISSUE THREAD

**Issue by Tokeii0** [ufrisk/MemProcFS#283] opened 2024-04-14 14:24 UTC
==============================  MemProcFS  ==============================
 - Author:           Ulf Frisk - pcileech@frizk.net
 - Info:             https://github.com/ufrisk/MemProcFS
 - License:          GNU Affero General Public License v3.0
   ---------------------------------------------------------------------
   MemProcFS is free open source software. If you find it useful please
   become a sponsor at: https://github.com/sponsors/ufrisk Thank You :)
   ---------------------------------------------------------------------
 - Version:          5.8.9 (Windows)
 - Mount Point:      M:\
 - Tag:              7601_b0806edb
 - Operating System: Windows 6.1.7601 (X64)
==========================================================================

[FORENSIC] FC_VIRTMEM_SCAN: INIT TOTAL:  ranges=5193, bytes=df1c2000
[INFODB]   INIT: SUCCESS: va=0xfffff880018f1000
[FORENSIC] FC_VIRTMEM_SCAN: FINISH
[FORENSIC] INIT COMPLETED : time=4s

"M:\sys\net\netstat-v.txt"
![image](https://github.com/ufrisk/MemProcFS/assets/111427585/c974728a-908e-405a-9eef-d77ef8d3eb43)

**Comment by ufrisk** [comment] 2024-04-15 15:52
MemProcFS Windows 7 support isn't top notch unfortunately. I created this tool around 2018 and onwards and Windows 7 was never a big focus since it was quite old already by then.

I'll look into why this is missing though. Maybe there is something I can do about it.

Thanks for letting me know.

**Comment by ufrisk** [comment] 2024-10-22 18:13
I did some updates for Windows 7 networking, can you see if it's working better now?

Windows XP isn't really supported though.

Also when listening there isn't a destination address and port. It's empty even on Windows.

Can you please confirm if it's now working or not?

**Comment by Tokeii0** [comment] 2024-10-24 05:16
I have tested several Windows 7 version memory images and the IP address can be displayed normally.
Thanks for the fix.
![image](https://github.com/user-attachments/assets/65a5d947-2027-4a3f-a9d4-949a0db1cf50)

**Comment by ufrisk** [comment] 2024-10-24 07:21
Thank you for confirming. This is great news. Apologies it took so long for me to look into it.

Since the issue is now resolved I'm closing the issue.

**Closed by ufrisk** 2024-10-24 07:21 UTC
Labels: enhancement
