### ISSUE TITLE
How can i call the function MMiscProcInfo_InitializeDTB in c++?

### ISSUE THREAD

**Issue by fortnitebott** [ufrisk/MemProcFS#173] opened 2023-04-11 06:40 UTC
https://github.com/ufrisk/MemProcFS/blob/d08e667af3456c0a044595e48b03af26d68100bc/vmm/modules/m_misc_procinfo.c#L25%5C

**Comment by ufrisk** [comment] 2023-04-11 15:20
That module is available as a file system module for the MemProcFS virtual file system. It's not directly accessible via an API function.

1) You can either mount the memory using MemProcFS.exe and then observe the module behavior (it takes a short while to render) and then open the file system file in C++. It's located at: `M:\misc\procinfo\`

2) You may use the VMMDLL file system API. This way you don't have to install the file system driver and mount it as a drive. First you'd need to initialize plugins (only once) with `VMMDLL_InitializePlugins()` then list files (and their sizes) with `VMMDLL_VfsListU()` and read files with `VMMDLL_VfsReadU()` The file will to read in this case would be named `\misc\procinfo\dtb.txt`.

**Comment by fortnitebott** [comment] 2023-04-12 19:38
![IMG_20230412_223812_731](https://user-images.githubusercontent.com/60422445/231566368-3e45d943-2bec-4b57-80a1-2df6e8305a30.jpg)
File dtb.txt empty

**Comment by ufrisk** [comment] 2023-04-12 19:42
what does progress_percent.txt say? it takes a short time to complete processing before results show up.

**Comment by fortnitebott** [comment] 2023-04-12 19:44
![IMG_20230412_224447_557](https://user-images.githubusercontent.com/60422445/231567932-c069993d-f581-4557-9b46-49d4817e2390.jpg)

**Comment by unemknip** [comment] 2023-04-13 21:54
> Did you resolve this? i.e. wait until the progress_percent.txt got to 100%?

Sorry to interrupt your dialog, maybe I'm just in the middle of something similar to TS, is it possible to read dtb.txt without opening VMM_INIT thread via Memprocfs, I'm fixing a broken dtb and I need to parse dtb.txt

I've tried the following but I always get FAIL
```
    NTSTATUS nt;
    DWORD i;
    BYTE pbPage1[0x1000];

    printf("CALL: VMMDLL_VfsReadU\n");
 
    nt = VMMDLL_VfsReadU(hVMM, LPSTR("\\\misc\\\procinfo\\\dtb.txt"), pbPage1, 0xfff, &i, 0);
    if (nt == SystemCoreSTATUS_SUCCESS) 
   {
        printf("SUCCESS: VMMDLL_VfsReadU\n");
        printf("%s", (LPSTR)pbPage1);
    }
    else {
        printf("FAIL: VMMDLL_VfsReadU\n"); 
    }

```
Maybe I need to turn memprocfs into a library and plug it into my project or not?

**Comment by unemknip** [comment] 2023-04-14 05:15
I'll add some information to my problem. I used code from VMM_EXAMPLE and it seems to work. But the fact is that the dtb.txt file always weighs 0kb, the progress.txt file weighs 1 kb, I even tried to do a receive in a loop to check if the information is updated over time, but no, it doesn’t work

**Comment by ufrisk** [comment] 2023-04-14 06:32
@unemknip it will start processing on the first access of one of these files.

After that you'd need to Sleep some substantial amount of time, like at least 100ms and try reading again. Processing should take like 10-30 seconds if things go well. And you should be able to monitor the progress by reading progress_percent.txt. The Sleep is very important.

Also reading may also return VMMDLL_STATUS_END_OF_FILE sometimes on success so you'd need to check for that as well.

I should probably add an example to this for this particular file in the vmm examples.

**Comment by unemknip** [comment] 2023-04-14 15:26
@ufrisk Thanks for your answer, I have already tried sleeping and differentiating conditions, sizes and stuff. I read all other files well, but I see some problems with progress_percent.txt and dtb.txt. Maybe I don’t understand something or there is some problem in the library, I’m not entirely sure.

I'm fixing the DTB manually and it works great, the only problem now is parsing the file.

Perhaps there are other methods of fixing DTB? Or maybe i can parse in another way? I just do not want to resort to crutches with copying the file through the Windows tools and backup it

**Comment by unemknip** [comment] 2023-04-15 16:19
The bug is fixed by adding Sleep(500) after VMMDLL_InitializePlugins, thanks to one of your discord guys, I hope this info helps other people too

**Comment by ufrisk** [comment] 2023-04-15 16:23
@unemknip I'm glad to see the issue is resolved, and thanks for the update :) Hopefully the DTB module will be of use. I'll publish an example about how to do this in the example project in the next release as well.

**Comment by ufrisk** [comment] 2023-04-15 18:42
And I've updated the example file at: https://github.com/ufrisk/MemProcFS/blob/0d535cc28dc132ecda475d328216319c6fae4029/vmm_example/vmmdll_example.c#L1428

The key when using this from the API seems to be doing some Sleep after the first read, otherwise the separate processing thread doesn't seem to start. Dunno why this is, but it's not an issue if you know about it I guess.

I'm closing this issue since it's now (hopefully) resolved.

Please let me know if there should be any lingering issues around this.

**Closed by ufrisk** 2023-04-15 18:42 UTC

**Comment by FocuzJS** [comment] 2023-04-16 15:31
@ufrisk In case you were wondering this code helps them locate the DTB on EasyAntiCheat after it's been relocated due to the new physical page being marked as a System PTE still. 🤣 Was crazy to see you committed this code the exact day I wrote something similar.

**Comment by ufrisk** [comment] 2023-04-16 18:06
oh, that was it was about, it would explain quite a few things. thought it was some kind of new malware (in a sense I guess you can call it that, and it's probably just a matter of time before it's used for that as well)... but why the sudden interest in this? This was something I added way back.

**Comment by FocuzJS** [comment] 2023-04-17 17:47
I imagine they just searched your repositories for "DTB" and stumbled on this working solution to their problems. Not sure how much you know about the actual thing they are trying to defeat but you can read some technical details about it here: https://www.unknowncheats.me/forum/anti-cheat-bypass/561736-analyzing-easyanticheats-cr3-protection.html essentially they are using some infinity hook esque technique to hook exceptions in the kernel globally, then they proceed to overwrite the DirectoryTableBase of the KPROCESS they are protecting to something that will trigger exceptions whenever the system tries to load it into CR3 and from their hook they set the correct one. Initially you fixed this by adding a validation to the DTB so that if memprocfs was started before the anticheat applied their protection, the invalid DTB would no longer break memprocfs's cache. To address their they *somehow* furthered the solution by reserving a new home for the PML4 entry at a new physical address. However as you can imagine this is wildly unsupported by Microsoft and I assume to try and stay compatible and not have to catch more exceptions (just my assumption), the new physical address is marked as a System PTE in the PfnDatabase. That's why your code is able to locate the correct DTB and also why you've recently also been asked to add support for the VMMDLL_OPT_PROCESS_DTB ConfigSet option. Hope this transparency helps you in some way. Thanks again for all the work you've put into these repositories; there's really some amazing code in here.

**Comment by FocuzJS** [comment] 2023-04-28 08:55
I imagined correctly as he is now trying to make it harder for people to discover this issue that he needed help with to begin with🤣
