### ISSUE TITLE
Python API module.maps.sections()  error

### ISSUE THREAD

**Issue by hx4477** [ufrisk/MemProcFS#338] opened 2024-11-15 15:18 UTC
Hello, I really like your project, but module.maps cannot be used. What is the reason for this?
The error code is as follows:

 module.maps.sections()
    ^^^^^^^^^^^
SystemError: error return without exception set

**Comment by ufrisk** [comment] 2024-11-15 18:07
Can you try the updated version (5.12.7), I fixed a bug around this.

Than You for reporting this issue.

**Comment by hx4477** [comment] 2024-11-16 03:39
Thank you very much for your reply, The problem ended after upgrading to version (5.12.7).

**Comment by ufrisk** [comment] 2024-11-16 11:24
Thank you for confirming it now works and thank you for reporting the issue. Since the issue is now resolved I'll be closing the ticket.

**Closed by ufrisk** 2024-11-16 11:24 UTC
Labels: bug
