### ISSUE TITLE
Slight instability in Win11 22H2

### ISSUE THREAD

**Issue by imerzan** [ufrisk/MemProcFS#139] opened 2022-10-07 00:47 UTC
Hi Ulf - I saw you added 22H2 support in memprocfs 5.1 , and have been testing it out. It mostly seems good, but I have noticed that occasional reads error out (that didn't happen in the prior branch of Windows 11)

Running `-vv` in my init, I captured my output and noticed a lot of the following throughout runtime.

```
[VMM]      MmWin_CompressedPage: FAIL: #42 UnsupportedPageRecord    // A couple of these
[VMM]      MmWin_CompressedPage: FAIL: #11 BTreeSearch    // Quite a few of these
[VMM]      MmWin_CompressedPage: FAIL: #35 ChunkArrayTooLarge    // TONS of these
```

Some details on my setup:
- my FPGA Firmware is version 4.7 at the moment (haven't been able to update it).
- Using Vmmsharp
- I am using the `symsrv` and `dbghlp` libs that are included with the release.
- I am using a Memory Map and verified it to be correct
- Default FPGA algo (0)

In earlier versions of Windows I was having issues with some of the same errors, disabling Memory Compression via this command fixed it `powershell Disable-MMAgent -mc` . Not sure if this is now causing issues. Also not sure how I'm getting CompressedPage errors with compression disabled =/

From the timeline that I was able to establish, most of the instability seems to occur when these show up
`[VMM]      MmWin_CompressedPage: FAIL: #11 BTreeSearch`

Towards the end of my debug session I had dozens of these, and it coincided with memory not being read at all for 2-4 seconds.

Not sure if you have any insight into the above errors, or if there is a Windows setting I should adjust for 22H2.

Once again, thanks for all of your work :)

EDIT: I rolled back to `WIN11 21H2` and **all** the fails went away.

**Comment by ufrisk** [comment] 2022-10-07 06:59
The unsupported page records have always been there. I just changed the error message in the update. I'm just not quite sure what to do about these.

The other two are probably due to additional changes for the memory compression in 22H2 that I missed in my initial testing.

Can you see if you have any successful memory decompression in the file M:\conf\statistics.txt in MemProcFS virtual file system?

**Comment by ufrisk** [comment] 2022-10-08 18:53
The majority of the paged memory failing the memory compression is memory that have been discarded and is backed by a file it seems like.

Example, if a memory is backed by a registry hive file which haven't changed in memory it may be discarded from memory and the OS will reload it from the on-disk registry hive file on next access.

I'll make it so that this memory will fail at the proper place and not go down the memory decompression route (which is wrong). Sadly it will even fail even after the update.

I'll make a minor update quite soon, and it will be interesting to see if you still have a lot of memory decompression errors after that (i.e. additional issues) or if this change will cover it all.

**Comment by imerzan** [comment] 2022-10-08 19:27
Hi Ulf - Thanks for the responses! Sorry I haven't had much time with work to upgrade back to 22H2 and check on the statistics.

I am surprised about this behavior, but I may not understand fully. I am reading memory allocated in User Mode, so not sure why the registry hive would be involved here. 

When you say "it will even fail after the update", is this due to differences in how Windows handles memory in 22H2? Because I tried analyzing the same memory on 21H2 and it works just fine.

I'll keep an eye out for an update, and re-check.

**Comment by ufrisk** [comment] 2022-10-08 19:30
The registry was an example. In user mode parts of a DLL may be discarded as an example if it's backed by the DLL on disk anyway.

I'll let you know where when I make the update.

**Comment by ufrisk** [comment] 2022-10-09 11:51
Is it working any better for you in the version I just published?

It should fail those memory reads gracefully now. You should see this in `M:\conf\statistics.txt` as READ FAIL: FileMapped

Are you still experiencing a lot of issues with regards to compressed memory fails? (a few are quite normal).

**Comment by imerzan** [comment] 2022-10-09 17:04
@ufrisk I tested it on 21H2 , zero fails (same behavior), which is good.

Trying on 22H2, I am seeing a LOT less failures, however i see a string of 3-4 `[VMM]      MmWin_CompressedPage: FAIL: #11 BTreeSearch` errors before each process refresh, but I haven't noticed any serious drop outs yet, but am still continuing to test...

**Comment by imerzan** [comment] 2022-10-09 17:29
Yeah not seeing huge problems, except minor blips before refreshes that weren't there before.

I mounted my fpga device using `memprocfs.exe -mount s -device fpga`

Inspected the stats file as you requested, and didn't see any huge issues. Wasn't sure how to get my device to run a dump or something, so I think it's just sitting refreshing the process tables.

```
VMM STATISTICS   (4kB PAGES / COUNTS - HEXADECIMAL)
===================================================
PHYSICAL MEMORY:                      
  READ CACHE HIT:                          117de
  READ RETRIEVED:                           81ed
  READ FAIL:                                   1
  WRITE:                                       0
PAGED VIRTUAL MEMORY:                 
  READ SUCCESS:                                c
    Prototype:                                 0
    Transition:                                c
    DemandZero:                                0
    VAD:                                       0
    Cache:                                     0
    PageFile:                                  0
    Compressed:                                0
  READ FAIL:                                   0
    Cache:                                     0
    VAD:                                       0
    FileMapped:                                0
    PageFile:                                  0
    Compressed:                                0
TLB (PAGE TABLES):                    
  CACHE HIT:                               42e36
  RETRIEVED:                                1a27
  FAILED:                                      0
PHYSICAL MEMORY REFRESH:                     5aa
TLB MEMORY REFRESH:                           d9
PROCESS PARTIAL REFRESH:                      3a
PROCESS FULL REFRESH:                         1d
```

**Comment by imerzan** [comment] 2022-10-09 17:37
OK, I deleted my `\Symbols` cache, and now it seems to be working fine. Not seeing any failures.

I wonder if it was using cached symbols from the last build of Windows... Thoughts?

**Comment by ufrisk** [comment] 2022-10-09 17:55
You can try to start it in "forensic mode" as well, that will kick off a lot of analysis stages. i.e. `memprocfs -device fpga -forensic 1`. But it's good to see the issue is mostly gone away at least :) Maybe it was the symbol issue as you mention even though I don't see why or how that could be.

**Comment by imerzan** [comment] 2022-10-09 18:13
Oh, that's good to know! Thank you.

Yeah, I'm not sure why, but this seems to be resolved now. The updated `vmm.dll` made all the difference -- thank you!

**Comment by imerzan** [comment] 2022-10-10 03:14
May not be out of the woods yet. I was noticing problematic behavior again, and saw a ton of `[VMM]      MmWin_CompressedPage: FAIL: #35 ChunkArrayTooLarge`

Ran the forensic command like you mentioned, and noticed there are a lot of failures:

Including `Device Info: FPGA: Bad PCIe TLP received! Should not happen!`

```
VMM STATISTICS   (4kB PAGES / COUNTS - HEXADECIMAL)
===================================================
PHYSICAL MEMORY:                      
  READ CACHE HIT:                         f45f51
  READ RETRIEVED:                         528aac
  READ FAIL:                               35f63
  WRITE:                                       0
PAGED VIRTUAL MEMORY:                 
  READ SUCCESS:                           1291fa
    Prototype:                             eea78
    Transition:                            35bf5
    DemandZero:                                d
    VAD:                                    43cf
    Cache:                                   442
    PageFile:                                  0
    Compressed:                              36f
  READ FAIL:                               82519
    Cache:                                  1404
    VAD:                                     a71
    FileMapped:                            7fe12
    PageFile:                                183
    Compressed:                              70f
TLB (PAGE TABLES):                    
  CACHE HIT:                             38425cf
  RETRIEVED:                                1a1c
  FAILED:                                      0
PHYSICAL MEMORY REFRESH:                     13b
TLB MEMORY REFRESH:                           2f
PROCESS PARTIAL REFRESH:                       c
PROCESS FULL REFRESH:                          6

```

**Closed** 2022-10-12 19:10 UTC

**Comment by ufrisk** [comment] 2022-10-14 16:53
Are you able to send me a full memory dump file when this issue when the ChunkArrayTooLarge occurs?

(if you're able to do the dump and then verify it gives you this issue when running MemProcFS forensic mode against it)?

The FileMapped issue I won't be able to fix (I'm almost certain of it) but this ChunkArrayTooLarge seems fixable (hopefully).

**Comment by imerzan** [comment] 2022-12-19 03:20
@ufrisk Just wanted to follow up and let you know that I re-tested Windows 11 using 5.1.5 and everything seems to be working properly on Windows 11 22H2. Thanks for all your hard work on this!
