### ISSUE TITLE
Invalid AddrBase from VMMDLL_ProcessGetMemoryMap ?

### ISSUE THREAD

**Issue by bin5k** [ufrisk/MemProcFS#14] opened 2019-11-02 20:19 UTC
recently i had some crashes and then i noticed that the AddrBase i get from VMMDLL_ProcessGetMemoryMap is not really correct, i have checked with VMMap (https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap) and it's seems so.

![buga](https://user-images.githubusercontent.com/44826092/68076542-c81ca200-fdad-11e9-80be-9ee03b00744b.png)

am i missing something ?

**Comment by ufrisk** [comment] 2019-11-02 20:47
The MemProcFS memory map is generated from the in-memory page tables that the CPU uses when translating virtual memory to physical memory.

The VMMap memory map is generated from Windows Virtual Address Descriptors (VADs) that include, for user mode processes, paged out memory and not yet committed memory that is not shown in the current MemProcFS memory map.

I'm actually in the midst of a major rewrite of the underlying virtual memory layer in MemProcFS, and once finished (hopefully before end of the year) it's going to include a separate VAD map similar to VMMap.

This is _not_ explaining any crashes you have though - so I'm guessing a separate issue here. It's really hard for me to track the crash issue down unless I have a way to reproduce it. If you're able to locate it or successfully reproduce it - it would be super nice, or else we'll wait and see if it goes away when my memory subsystem rewrite is finished.

**Comment by bin5k** [comment] 2019-11-02 21:16
I see, i totally forgot about the VAD Descriptors.
About the crashes, it is related to the AddrBase because my program was expecting addresses similar to the ones in VMMap.
For now i think i will just walk the VAD myself until you have rewrite done.

**Comment by ufrisk** [comment] 2019-12-05 21:25
I'm closing this issue since VADs are supported since v3.0 released a few days ago.

**Closed by ufrisk** 2019-12-05 21:25 UTC
Labels: enhancement
