### ISSUE TITLE
add fflush to file logging

### ISSUE THREAD

**Issue by maoxian123** [ufrisk/MemProcFS#251] opened 2023-12-20 09:29 UTC
```
LPSTR args[] = { (LPSTR)"-device", (LPSTR)"fpga",(LPSTR)"-loglevel",(LPSTR)"4"};
    hVmm = VMMDLL_Initialize(4, args);
```
this code output
```
[INFODB]   INIT: FAIL: va=0xfffff8016fc00000
[SYMBOL]   Functionality may be limited. Extended debug information disabled.
[SYMBOL]   Offline symbols unavailable - ID: 7D02613E1047000
[SYMBOL]   Reason: Could not load PDB required file - symsrv.dll/dbghelp.dll.
[SYMBOL]   Reason: Could not load PDB required file - libpdbcrust.dll/so.

[+] vmm.dll initialized![CORE]     VmmProc: Start periodic cache flushing
```
it is normal

but 
```
LPSTR args[] = { (LPSTR)"-device", (LPSTR)"fpga",(LPSTR)"-loglevel",(LPSTR)"f::4",(LPSTR)"-logfile",(LPSTR)"memprocfslog.txt"};
    hVmm = VMMDLL_Initialize(6, args);
```
it will create a file,but not write anyting,and the cmd output is null too.

**Comment by ufrisk** [comment] 2023-12-20 11:36
Use `f:4` to log with verbose level to the file. There was an error in [the guide](https://github.com/ufrisk/MemProcFS-dev/wiki/_CommandLine#-loglevel) previously which I've now resolved.

The file is not regularly flushed though so results may not be instantly visible. I should probably change that or at least add a force flush option, but it may also slow down execution significantly at the higher log levels so an option to flush after each log may be good.

If using the API on-screen console logging isn't enabled by default. You'd either have to enable it with the old way, i.e. command line options -printf and -v.

But since you're using the newer loglevel option it would be: `f:4,4` if wishing to log at verbose level to both file and on-screen.

Let me know if it works better.

**Comment by maoxian123** [comment] 2023-12-25 07:41
it works,but only when the handle of hVmm close,it will flush,i recommend add a flush interval.

**Comment by ufrisk** [comment] 2023-12-25 11:30
I'll add a flush, possibly via some extra config option. I'm currently away over holidays though so it will have to wait until I get back home since my code signing certificate is on another computer.

**Comment by ufrisk** [comment] 2024-02-06 23:37
I added this some time ago, but I forgot to update the documentation and also mention it here.

Nevertheless, there should now be a `fflush` option to the `-loglevel` option. See the documentation (click details): https://github.com/ufrisk/MemProcFS-dev/wiki/_CommandLine#-loglevel

It will do a fflush after each written log line if specified.

In your above example it should be like this now:
```
LPSTR args[] = { (LPSTR)"-device", (LPSTR)"fpga",(LPSTR)"-loglevel",(LPSTR)"fflush,f::4",(LPSTR)"-logfile",(LPSTR)"memprocfslog.txt"};
    hVmm = VMMDLL_Initialize(6, args);
```

I'm closing this issue since it should now be resolved. But if there should be any lingering issues or not work as intended please let me know and feel free to re-open the issue.

**Closed by ufrisk** 2024-02-06 23:37 UTC
Labels: enhancement
