### ISSUE TITLE
Error message shown at start-up.

### ISSUE THREAD

**Issue by ironman97** [ufrisk/MemProcFS#142] opened 2022-10-23 05:35 UTC
![pic](https://user-images.githubusercontent.com/38624406/197375713-3ebc8868-f932-4892-be2b-b7e13adbc0f6.png)

**Comment by ufrisk** [comment] 2022-10-23 08:08
Hi,

That is a bad error message that I will remove in the next version. Just please disregard it for now. If you really wish to get rid of it adding the option `-disable-python ` may do it (I'm not completely sure about this though).

Anyway, no worries about this one.

I'll put it up as a bug though so I remember to fix it.

**Comment by ufrisk** [comment] 2022-11-16 16:19
I hope this should have gone away now. Is it working better now?

NB! if you have some older python packages of memprocfs you may have to update them to the latest version with python pip or uninstall them.

**Comment by ironman97** [comment] 2022-11-19 03:16
It is working better now. Thank you!

**Comment by ufrisk** [comment] 2022-11-19 13:26
Huge thanks for confirming it's now working. Please let me know if you should run into any other issues or if you come to think of any features that you feel should be added.

Since the issue is now resolved I'm closing the issue.

**Closed by ufrisk** 2022-11-19 13:26 UTC
Labels: bug
