### ISSUE TITLE
Disconnecting within seconds

### ISSUE THREAD

**Issue by caiovlp** [ufrisk/MemProcFS#245] opened 2023-12-03 21:36 UTC
Hi there!

I've been using Memproc/pcileech for a while and it's been working great. I tried to move the Screamer Squirrel that's been working fine to a new computer and having some weird issues. The connection works great, I'm able to pcileech dump without problems. Memproc fails within seconds though. I'm able to hear the USB disconnecting beep but I get different errors when I look at the logs:

When I use -vvv and call `VMMDLL_Initialize`, it fails before completing:
```TX: MRd64:  Len: 000 ReqID: 0900 BE_FL: ff Tag: dc Addr: 000000089da3e000
0000    20 00 00 00 09 00 dc ff  00 00 00 08 9d a3 e0 00    ...............

TX: MRd64:  Len: 000 ReqID: 0900 BE_FL: ff Tag: dd Addr: 000000089da3d000
0000    20 00 00 00 09 00 dd ff  00 00 00 08 9d a3 d0 00    ...............
[CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
VmmProc: Unable to auto-identify operating system.
         Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
         If arm64 dump, specify architecture: -arch arm64
[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (000001D0AE945040).
[CORE]       TIME: 2023-12-03 21:09:03 UTC.
[CORE]       RUNTIME: 7s.
```

when I use -vv, most of the time `VMMDLL_Initialize` runs successfully but errors a few seconds later:
```
[PDB]      Functionality may be limited. Extended debug information disabled
[PDB]      Offline symbols unavailable - file 'info.db' not found
[PDB]      Reason: Could not load PDB required files - symsrv.dll/dbghelp.dll.

Initialized 64-bit Windows 10.0.22621
DMA initialized successfully
[CORE]     VmmProc: Start periodic cache flushing
Processes:
   11192    Notepad.exe 0 18984
Process found: 11192
[REGISTRY] CM.Sig   000, CM.Len0   118, CM.StorMap0  120, CM.StorSmallDir0 128, CM.BaseBlock 040
[REGISTRY]               CM.Len1   390, CM.StorMap1  398, CM.StorSmallDir1 3A0, HE._Size     018
[REGISTRY] CM.FLAll 648, CM._Size  760, CM.FileFull  720, CM.FileUserPath  730, CM.HiveRoot  740
[REGISTRY] BB.Sig   000, BB.Length 028, BB.FileName  030, BB.Major         014, BB.Minor     018
[REGISTRY] HIVE_ENUM: 0001: 0xffffe48843254000-d793dcf70ea09d96COM15dat-WC_Silod9111165-87a4-752c-a711-e58ed73cb7abcom
[REGISTRY] HIVE_ENUM: 0002: 0xffffe48843252000-d793dcf70ea09d96dat-WC_Silo8ee511a7-3cd7-abb7-6511-11d9a4872c75software
[REGISTRY] HIVE_ENUM: 0003: 0xffffe4883f841000-d793dcf70ea09d96dat-WC_Silo8ee511a7-3cd7-abb7-6511-11d9a4872c75com
[REGISTRY] HIVE_ENUM: 0004: 0xffffe48833316000-ActivationStoredat-A_{8322F606-D61C-4ABF-AD4B-AE7A00F23A48}
[REGISTRY] HIVE_ENUM: 0005: 0xffffe4883d8dd000-ActivationStoredat-A_{AFCBF39F-1251-4EF8-A058-4CD452585500}
[REGISTRY] HIVE_ENUM: 0006: 0xffffe48840068000-settingsdat-A_{cc3b5214-09d4-dea3-4765-dbc1f62a1104}
[REGISTRY] HIVE_ENUM: 0007: 0xffffe488480bd000-settingsdat-A_{7b22d19a-9d21-4a2c-cc7a-cc082dd31371}
[REGISTRY] HIVE_ENUM: 0008: 0xffffe4884437a000-BCD-MACHINE_BCD00000000
[REGISTRY] HIVE_ENUM: 0009: 0xffffe4883cdc0000-ActivationStoredat-A_{86B8CD81-8BEB-4A74-844F-115511AA3C40}
[REGISTRY] HIVE_ENUM: 0010: 0xffffe4884da81000-ActivationStoredat-A_{745021C2-DA43-4232-8534-CFBA7C5BAD6D}
[REGISTRY] HIVE_ENUM: 0011: 0xffffe48834bf0000-ActivationStoredat-A_{21E5BB85-B6D9-4195-81EC-62D0FA16664C}
[REGISTRY] HIVE_ENUM: 0012: 0xffffe488361b5000-settingsdat-A_{eef3d418-ec8f-918b-a1df-4f1bee7daaad}
[REGISTRY] HIVE_ENUM: 0013: 0xffffe48834acd000-ff0098172674f107dat-WC_Silo4d29fb69-9faa-74c2-6511-11d9a4872c75software
[REGISTRY] HIVE_ENUM: 0014: 0xffffe488421d0000-11e887ee554bc76cdat-WC_Silof0441f4b-38ca-2a0c-6511-11d9a4872c75com
[REGISTRY] HIVE_ENUM: 0015: 0xffffe4883f7ec000-Userdat-WC_Silo4d29fb69-9faa-74c2-6511-11d9a4872c75user_sid
[REGISTRY] HIVE_ENUM: 0016: 0xffffe488377d9000-11e887ee554bc76cCOM15dat-WC_Silod9111165-87a4-752c-4b1f-44f0ca380c2acom
[REGISTRY] HIVE_ENUM: 0017: 0xffffe4883c5d4000-UserClassesdat-WC_Silo4d29fb69-9faa-74c2-6511-11d9a4872c75user_classes
[REGISTRY] HIVE_ENUM: 0018: 0xffffe48841bd2000-UserClassesdat-WC_Silof0441f4b-38ca-2a0c-6511-11d9a4872c75user_classes
[REGISTRY] HIVE_ENUM: 0019: 0xffffe48843b1b000-ff0098172674f107COM15dat-WC_Silod9111165-87a4-752c-69fb-294daa9fc274com
[REGISTRY] HIVE_ENUM: 0020: 0xffffe488425ab000-Userdat-WC_Silof0441f4b-38ca-2a0c-6511-11d9a4872c75user_sid
[REGISTRY] HIVE_ENUM: 0021: 0xffffe48843469000-ff0098172674f107dat-WC_Silo4d29fb69-9faa-74c2-6511-11d9a4872c75com
[REGISTRY] HIVE_ENUM: 0022: 0xffffe48833457000-11e887ee554bc76cdat-WC_Silof0441f4b-38ca-2a0c-6511-11d9a4872c75software
[REGISTRY] HIVE_ENUM: 0023: 0xffffe48850d36000-ActivationStoredat-A_{D2DFC5F4-34E5-4EAF-84F8-129912D7B85A}
[REGISTRY] HIVE_ENUM: 0024: 0xffffe4884395e000-ActivationStoredat-A_{D777970A-0275-47F1-BE46-81BE46206B9D}
[REGISTRY] HIVE_ENUM: 0025: 0xffffe4883f0cb000-settingsdat-A_{c1b00d21-e60c-0a25-7a67-5ac69ce18096}
[REGISTRY] HIVE_ENUM: 0026: 0xffffe4884395b000-settingsdat-A_{d3535e59-ccbf-1145-036a-91080766bebe}
[REGISTRY] HIVE_ENUM: 0027: 0xffffe4884f62a000-ActivationStoredat-A_{95630338-3AC0-45D7-939E-4BEADE50ACD9}
[REGISTRY] HIVE_ENUM: 0028: 0xffffe48843851000-ActivationStoredat-A_{5AE5C57A-39BD-43C4-BB16-AA5C22006C3B}
[REGISTRY] HIVE_ENUM: 0029: 0xffffe4884462f000-ActivationStoredat-A_{F257626B-26DE-47FE-8B00-1EAE87D675A2}
[REGISTRY] HIVE_ENUM: 0030: 0xffffe4883c9f2000-ActivationStoredat-A_{B8E980E2-2782-47A4-BB4E-B24A98D08218}
[REGISTRY] HIVE_ENUM: 0031: 0xffffe4884c409000-ActivationStoredat-A_{F2C0899E-00B3-43D6-90CB-83E079C0916D}
[REGISTRY] HIVE_ENUM: 0032: 0xffffe48835f58000-ActivationStoredat-A_{CA1D9579-D846-4FA1-BD4E-D1441051D698}
[REGISTRY] HIVE_ENUM: 0033: 0xffffe4884cec6000-ActivationStoredat-A_{30D7D523-F5E2-41E9-AF90-9641BC6DECDC}
[REGISTRY] HIVE_ENUM: 0034: 0xffffe48835f28000-ActivationStoredat-A_{457C9E40-7782-49B2-913F-738288C848BE}
[REGISTRY] HIVE_ENUM: 0035: 0xffffe488515a2000-settingsdat-A_{0353aa7f-f800-e277-e9cf-2d27d730cbf5}
[REGISTRY] HIVE_ENUM: 0036: 0xffffe48830843000-ActivationStoredat-A_{29C73C60-58D5-46E1-87FF-65626A781CE3}
[REGISTRY] HIVE_ENUM: 0037: 0xffffe4885160b000-5182a531862f9de7dat-WC_Silobc36307d-c177-208e-6511-11d9a4872c75software
[REGISTRY] HIVE_ENUM: 0038: 0xffffe488404da000-UsrClassdat-USER_S-1-5-21-1828722664-3040598951-1713776511-1001_Classes
[REGISTRY] HIVE_ENUM: 0039: 0xffffe4885160d000-5182a531862f9de7COM15dat-WC_Silod9111165-87a4-752c-7d30-36bc77c18e20com
[REGISTRY] HIVE_ENUM: 0040: 0xffffe4883643c000-ntuserdat-USER_S-1-5-21-1828722664-3040598951-1713776511-1001
[REGISTRY] HIVE_ENUM: 0041: 0xffffe48851628000-5182a531862f9de7dat-WC_Silobc36307d-c177-208e-6511-11d9a4872c75com
[REGISTRY] HIVE_ENUM: 0042: 0xffffe4883626d000-Amcachehve-A_{b1586843-399d-8dd6-500e-19e6625ffbd7}
[REGISTRY] HIVE_ENUM: 0043: 0xffffe4885105f000-ActivationStoredat-A_{CBC43538-D153-4C4A-86A2-3804C8F72B38}
[REGISTRY] HIVE_ENUM: 0044: 0xffffe4884fcf1000-settingsdat-A_{7a8040f6-8a6b-f479-a59d-78f8674e255f}
[REGISTRY] HIVE_ENUM: 0045: 0xffffe4883369d000-NTUSERDAT-USER_S-1-5-19
[REGISTRY] HIVE_ENUM: 0046: 0xffffe488336e1000-BBI-A_{cc56c8f5-d68e-4cbe-a75b-f33ecb2e9575}
[REGISTRY] HIVE_ENUM: 0047: 0xffffe4882c882000-unknown-unknown
[REGISTRY] HIVE_ENUM: 0048: 0xffffe48833394000-NTUSERDAT-USER_S-1-5-20
[REGISTRY] HIVE_ENUM: 0049: 0xffffe488331ad000-SAM-MACHINE_SAM
[REGISTRY] HIVE_ENUM: 0050: 0xffffe48833107000-SECURITY-MACHINE_SECURITY
[REGISTRY] HIVE_ENUM: 0051: 0xffffe488308a4000-DEFAULT-USER_.DEFAULT
[REGISTRY] HIVE_ENUM: 0052: 0xffffe4882f4a2000-SOFTWARE-MACHINE_SOFTWARE
[REGISTRY] HIVE_ENUM: 0053: 0xffffe4882c861000-SYSTEM-MACHINE_SYSTEM
[REGISTRY] HIVE_ENUM: 0054: 0xffffe4882c94b000-unknown-MACHINE_HARDWARE
[REGISTRY] BAD HBIN HEADER: Hive=ffffe4882c94b000 HBin=0012d000 Sig=2f5c0070
[REGISTRY] BAD HBIN HEADER: Hive=ffffe4882c94b000 HBin=80004000 Sig=00010001
[REGISTRY] BAD HBIN HEADER: Hive=ffffe4882c94b000 HBin=80006000 Sig=00000102
[REGISTRY] BAD HBIN HEADER: Hive=ffffe4882c94b000 HBin=8000a000 Sig=00000003
```
 
I'm also trying attacking from the same computer - first time trying this but I doubt that's the issue.

**Comment by caiovlp** [comment] 2023-12-04 11:14
@ufrisk thanks for the response

I tried the first one and it didn't work:
```0x1000      0x9E000
0x9F000     0xA0000
0x100000    0x40D3B000
0x44FFF000  0x45000000
0x10000000  0x8B0800000```

It doesn't even load for a bit like without memmap:
```0000    00 00 00 00 09 00 76 ff  00 07 60 00               ......v...`.

TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 77 Addr: 00077000
0000    00 00 00 00 09 00 77 ff  00 07 70 00               ......w...p.

TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 78 Addr: 00078000
0000    00 00 00 00 09 00 78 ff  00 07 80 00               ......x.....

TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 79 Addr: 00079000
0000    00 00 00 00 09 00 79 ff  00 07 90 00               ......y.....
[CORE]     DTB  located at: 00000000001ae000. MemoryModel: X64
[PROCESS]  BAD DTB: PID=4 DTB=00000000001ae000
[CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
VmmProc: Unable to auto-identify operating system.
         Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
         If arm64 dump, specify architecture: -arch arm64
[CORE]     Failed to initialize.

[CORE]     SHUTDOWN COMPLETED (00000170F70AB040).
[CORE]       TIME: 2023-12-04 10:58:47 UTC.
[CORE]       RUNTIME: 1s.

Unable to initialize DMA``` 

I'll try the other one later today or tomorrow. It doesn't seem to me like the firmware is the issue if it works fine when targeting the same PC from another computer.

Another question - this is an Intel machine but I think the mobo ports are thunderbolt - I need to look at the specs. If that's the case, do you think connecting through a USB-C PCIE card would help?

**Comment by imerzan** [comment] 2023-12-04 18:21
> @ufrisk thanks for the response
> 
> I tried the first one and it didn't work:
> 
> ```
> 0x1000      0x9E000
> 0x9F000     0xA0000
> 0x100000    0x40D3B000
> 0x44FFF000  0x45000000
> 0x10000000  0x8B0800000
> ```
> 
> It doesn't even load for a bit like without memmap:
> 
> ```
> 
> TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 77 Addr: 00077000
> 0000    00 00 00 00 09 00 77 ff  00 07 70 00               ......w...p.
> 
> TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 78 Addr: 00078000
> 0000    00 00 00 00 09 00 78 ff  00 07 80 00               ......x.....
> 
> TX: MRd32:  Len: 000 ReqID: 0900 BE_FL: ff Tag: 79 Addr: 00079000
> 0000    00 00 00 00 09 00 79 ff  00 07 90 00               ......y.....
> [CORE]     DTB  located at: 00000000001ae000. MemoryModel: X64
> [PROCESS]  BAD DTB: PID=4 DTB=00000000001ae000
> [CORE]     Initialization Failed. Unable to locate ntoskrnl.exe. #3
> VmmProc: Unable to auto-identify operating system.
>          Specify PageDirectoryBase (DTB/CR3) in -dtb option if value if known.
>          If arm64 dump, specify architecture: -arch arm64
> [CORE]     Failed to initialize.
> 
> [CORE]     SHUTDOWN COMPLETED (00000170F70AB040).
> [CORE]       TIME: 2023-12-04 10:58:47 UTC.
> [CORE]       RUNTIME: 1s.
> 
> Unable to initialize DMA
> ```
> 
> I'll try the other one later today or tomorrow. It doesn't seem to me like the firmware is the issue if it works fine when targeting the same PC from another computer.
> 
> Another question - this is an Intel machine but I think the mobo ports are thunderbolt - I need to look at the specs. If that's the case, do you think connecting through a USB-C PCIE card would help?

Shave 1 byte off the top of each mem map entry, I didn't do that and had issues.
1000      - 9dfff
9f000     - 9ffff

etc.

**Comment by ufrisk** [comment] 2024-02-06 23:39
@caiovlp did you resolve this issue with the above help or is it still not working?

**Comment by caiovlp** [comment] 2024-02-12 14:06
memmap didn't work for me but I manage to work around this issue with pci-e usb-c card. Thanks for the help

**Comment by ufrisk** [comment] 2024-02-12 17:56
Many thanks for the update. It's nice to see the issue is resolved. I'm closing this issue.

**Closed by ufrisk** 2024-02-12 17:56 UTC

**Comment by Stan0585** [comment] 2024-11-27 21:37
![IMG_1449](https://github.com/user-attachments/assets/c6026650-d6b2-4fdd-9d85-2c8e8accd214)

**Comment by Stan0585** [comment] 2024-11-27 21:38
I’m new to this, and I’m getting this error.
