### ISSUE TITLE
Can DMA be read by multiple threads? Why is it slow? Can it be read without DMA?

### ISSUE THREAD

**Issue by bbhxwl** [ufrisk/MemProcFS#124] opened 2022-09-09 17:28 UTC
Can DMA be read by multiple threads? Why is it slow? Can it be read without DMA?
If I use multithreading to read DMA, it will be very slow, and it takes 3 seconds to read data. If I don't use multithreading, I can read data every 20 milliseconds. Why?

**Comment by imerzan** [comment] 2022-09-10 00:31
I can do DMA Reads across multiple threads just fine (on about 5 threads to be exact), not sure what the problem is.

**Comment by bbhxwl** [comment] 2022-09-10 02:28
> I can do DMA Reads across multiple threads just fine (on about 5 threads to be exact), not sure what the problem is on your end, but it's probably not the threads.

new Vmm("", "-device", "fpga");
Is this how you initialize it?

**Comment by imerzan** [comment] 2022-09-10 02:32
Did you read the examples at https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs ?

**Comment by bbhxwl** [comment] 2022-09-10 04:04
> Did you read the examples at https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs ?

Of course, I can't read the memory without reading it, can I? But the translation I use may not be so good

**Comment by bbhxwl** [comment] 2022-09-10 04:17
> Did you read the examples at https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs ?

 vmm.ConfigSet
Does this code have any function that can change the reading efficiency?

**Comment by bbhxwl** [comment] 2022-09-10 06:51
> Did you read the examples at https://github.com/ufrisk/MemProcFS/blob/master/vmmsharp/vmm_example.cs ?

![image](https://user-images.githubusercontent.com/26525599/189472741-6a1234e4-b900-4ffd-8f64-558e51544bf0.png)

**Comment by ufrisk** [comment] 2022-09-10 10:04
DMA accesses are serialized behind a lock. If multiple threads wish to do DMA at the very same time they'll be suspended waiting for the lock to be released. There is no fairness guarantee for which of the waiting threads will be woken so if having a large amount of threads waiting for DMA access it may take a long time for some.

Also there are some background tasks for refreshes as you already noticed.

If wanting to read a lot of different memory at the same time it's better to use the Scatter API for this and read many addresses in one single go.

**Comment by bbhxwl** [comment] 2022-09-10 13:59
> DMA accesses are serialized behind a lock. If multiple threads wish to do DMA at the very same time they'll be suspended waiting for the lock to be released. There is no fairness guarantee for which of the waiting threads will be woken so if having a large amount of threads waiting for DMA access it may take a long time for some.
> 
> Also there are some background tasks for refreshes as you already noticed.
> 
> If wanting to read a lot of different memory at the same time it's better to use the Scatter API for this and read many addresses in one single go.

I seem to use 4.9. Initialization is successful, but I can't get any PID

**Comment by bbhxwl** [comment] 2022-09-10 15:28
> DMA accesses are serialized behind a lock. If multiple threads wish to do DMA at the very same time they'll be suspended waiting for the lock to be released. There is no fairness guarantee for which of the waiting threads will be woken so if having a large amount of threads waiting for DMA access it may take a long time for some.
> 
> Also there are some background tasks for refreshes as you already noticed.
> 
> If wanting to read a lot of different memory at the same time it's better to use the Scatter API for this and read many addresses in one single go.

```
ulong pObjPointer = vmm.MemReadInt64(pid, actorBase + (ulong)i * 8);
 int actorId = (int)vmm.MemReadInt32(pid, pObjPointer + Offset_ObjID);
```
If I cycle 1000 times to read data. In each cycle, a fixed address is read, and then the previously read address + an offset are read. Is it not easy to use scatter? Because I feel that if the read address is fixed, scatter may be a good choice. I don't know how much efficiency this can improve?

**Comment by imerzan** [comment] 2022-09-10 15:40
I think you need to slow down, and play around with this codebase for like a week before you keep trying to continue. Because your questions are thick and coming fast, and a lot of this is documented in this repository.

As Ulf mentioned, scatter reads will increase performance. Let's say you have 5 addresses to read, and we'll use 0x0 as our base:

8 bytes at 0x0
8 bytes at 0x100
8 bytes at 0x200
8 bytes at 0x250
8 bytes at 0x900

Instead of doing 5 individual reads, you can read all of these in a SINGLE read since they are within the same page boundary (0x1000) of memory.

The new Scatter API that is documented in the example makes this extremely easy to achieve.

**Comment by bbhxwl** [comment] 2022-09-11 04:36
> ```cs
> // read two independent chunks of memory in one single efficient call.
>         // also use the nocache flag.
>         VmmScatter scatter = vmm.Scatter_Initia
> ```

```
 string name = vmm.MemReadString(pid, vmm.MemReadInt64(pid, pObjPointer + Offset_CharacterName), 64);
    
```                            
When I read the data once, I need to cycle all obj, probably about 1000. For example, each time I read a name, I will go to the address, and then read it with this address. There is a sequential relationship. If I cycle this 1000 times, I need to read 10 times of memory every time. Maybe I need to read 10000 times of memory every time. Then I can optimize it to cycle 10 times, reading 1000 memories in the same location dispersedly each time, right? I currently need 3000ms to read once

**Comment by bbhxwl** [comment] 2022-09-11 07:24
> I think you need to slow down, and play around with this codebase for like a week before you keep trying to continue. Because your questions are thick and coming fast, and a lot of this is documented in this repository.
> 
> As Ulf mentioned, scatter reads will increase performance. Let's say you have 5 addresses to read within an aligned page, and we'll use 0x0 as our base:
> 
> 8 bytes at 0x0 8 bytes at 0x100 8 bytes at 0x200 8 bytes at 0x250 8 bytes at 0x900
> 
> Instead of doing 5 individual reads, you can read all of these in a SINGLE read since they are within the same page boundary (0x1000) of memory. This greatly reduces contention for the FPGA device resources.
> 
> The new Scatter API that is documented in the example makes this extremely easy to achieve.
> 
> ```cs
>         // read two independent chunks of memory in one single efficient call.
>         // also use the nocache flag.
>         VmmScatter scatter = vmm.Scatter_Initialize(dwExplorerPID, Vmm.FLAG_NOCACHE);
>         if(scatter != null)
>         {
>             // prepare multiple ranges to read
>             scatter.Prepare(mModuleKernel32.vaBase, 0x100);
>             scatter.Prepare(mModuleKernel32.vaBase + 0x2000, 0x100);
>             // execute actual read operation to underlying system
>             scatter.Execute();
>             byte[] pbKernel32_100_1 = scatter.Read(mModuleKernel32.vaBase, 0x80);
>             byte[] pbKernel32_100_2 = scatter.Read(mModuleKernel32.vaBase + 0x2000, 0x100);
>             // clean up scatter handle hS (free native memory)
>             // NB! hS handle should not be used after this!
>             scatter.Close();
>         }
> ```



> DMA accesses are serialized behind a lock. If multiple threads wish to do DMA at the very same time they'll be suspended waiting for the lock to be released. There is no fairness guarantee for which of the waiting threads will be woken so if having a large amount of threads waiting for DMA access it may take a long time for some.
> 
> Also there are some background tasks for refreshes as you already noticed.
> 
> If wanting to read a lot of different memory at the same time it's better to use the Scatter API for this and read many addresses in one single go.

          ```
  scatter.Prepare(mModuleKernel32.vaBase, 0x100);
            scatter.Prepare(mModuleKernel32.vaBase + 0x2000, 0x100);
            scatter.Execute();
            byte[] pbKernel32_100_1 = scatter.Read(mModuleKernel32.vaBase, 0x80);
            byte[] pbKernel32_100_2 = scatter.Read(mModuleKernel32.vaBase + 0x2000, 0x100);


            scatter.Prepare(mModuleKernel32.vaBase+100, 0x100);
scatter.Execute();
            byte[] p = scatter.Read(mModuleKernel32.vaBase+100, 0x100);
```

What should I do if I finish reading and prepare to read others? It seems that the execution result indicates success, but nothing can be read from the memory

**Comment by ufrisk** [comment] 2022-09-11 18:32
You cannot do a call to `scatter.Prepare` after a call to `scatter.Execute`.

You'd need to either create a new scatter object or use the `Clear` function before doing another call to  `scatter.Prepare`.

Also when you're done with your scatter reads it may be a good idea to call `Close` to clean up some native resources. It should also clean up automatically when going out of scope.

**Comment by ufrisk** [comment] 2022-09-11 18:33
I hope my answers about the threading issue has been answered as well. I'm closing the issue.

**Closed by ufrisk** 2022-09-11 18:33 UTC

**Comment by bbhxwl** [comment] 2022-09-12 12:56
> You cannot do a call to `scatter.Prepare` after a call to `scatter.Execute`.
> 
> You'd need to either create a new scatter object or use the `Clear` function before doing another call to `scatter.Prepare`.
> 
> Also when you're done with your scatter reads it may be a good idea to call `Close` to clean up some native resources. It should also clean up automatically when going out of scope.
Closse and clear cannot replace re scatter_ Initialize


![image](https://user-images.githubusercontent.com/26525599/189659352-89489120-2355-4765-9f38-7b2ced11404e.png)

**Comment by ufrisk** [comment] 2022-09-15 18:37
After a `scatter.Close()` you won't be able to use this object any more. You would need to create a new one.

If wishing to reuse the same scatter object do a `scatter.Clear(pid, flags)` (without using close) before doing additional PrepareRead calls.
