### ISSUE TITLE
Getting fatal BSOD error: PAGE FAULT IN NONPAGED AREA

### ISSUE THREAD

**Issue by ullMarksin** [ufrisk/MemProcFS#158] opened 2022-12-21 07:12 UTC
Hello,
Environment: 
hyper-v VM -> c+ application with VMM + LiveCloudKd as -device 
static LPSTR args[3] = { (LPSTR)"", (LPSTR)"-device", (LPSTR)"hvmm://id=0" };
hVMM = VMMDLL_Initialize(3, args);

I am trying to figure out what causes windows OS crashes with BSOD fatal error.
Problem is that my application not always,but time from time crashes with BSOD PAGE FAULT IN NONPAGED AREA and its hard to identify where is the problem,  because its so randomly and my app 90% of time runs perfectly, I only read memory. 

Using: 
VMMDLL_MemReadEx(hVMM, process_id, address, (PBYTE)buffer, size, &dwBytesRead, 
		VMMDLL_FLAG_NOCACHE | VMMDLL_FLAG_NOCACHEPUT | VMMDLL_FLAG_ZEROPAD_ON_FAIL ))

Error:
![screenshot](https://user-images.githubusercontent.com/39835173/208840465-0f9b38dd-7fc1-47a9-9dca-7714b5aa6dac.JPG)

While from error its clearly crash is caused by hvmm.sys what is LiveCloudKd, its unclear why:

1) My code, because I read not accessible memory address? 
2) LiveCloudKd hvmm.sys buggy?
3) vmmdll.h bug?

Did vmmdll.h checks for not reading not accessible/out of range memory ? I didn't have deep understanding of system memory management and etc, so I have no idea how to check that, logically I expect that VMMDLL_MemReadEx()  will return false If I trying to read somewhere where I shouldn't. 

Error from event manager ( I can't share memory dump ):
The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000050 (0xffffffff000000f0, 0x0000000000000000, 0xfffff8038026161f, 0x0000000000000002). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: c3c90fa9-8c69-4140-b512-a896e9fe059e.

Any suggestion would be helpful.

**Comment by ullMarksin** [comment] 2022-12-21 07:21
Also tried to call VMMDLL_MemReadEx() with  additional VMMDLL_FLAG_NOPAGING_IO | VMMDLL_FLAG_NOPAGING flags, didn't solve the problem.

**Comment by ufrisk** [comment] 2022-12-21 16:14
You seem to have run into an issue with LiveCloudKd. Please raise an issue with the [LiveCloudKd](https://github.com/gerhart01/LiveCloudKd) repo to let @gerhart01 know about this.

Unfortunately there is nothing I can do about the MemProcFS code about this. The issue is not with MemProcFS itself.

**Comment by ullMarksin** [comment] 2022-12-21 19:05
ok thank you.

**Comment by ufrisk** [comment] 2022-12-21 21:41
👍  I wish there were more I could do, but this is outside my control. I'm closing this issue, but if it's fixed please let me know.

**Closed by ufrisk** 2022-12-21 21:41 UTC

**Comment by gerhart01** [comment] 2022-12-22 11:39
It will be good, if you show !analyze -v and vertarget WinDBG output for Hyper-V host OS MEMORY.DMP
