### ISSUE TITLE
VMMDLL_Initialize Failing with winpmem

### ISSUE THREAD

**Issue by zpacedesu** [ufrisk/MemProcFS#106] opened 2022-07-10 09:31 UTC
Hi,

I am currently trying to use winpmem with memproc in C++ and I am having troubles with initialization, any help would be appreciated! This was a quick code to test it, and I have had no luck with initialization

`	LPCSTR psz[4] = { "", "printf", "-device", "pmem://C:\winpmem_x64.sys" };

	bool result = VMMDLL_Initialize(4, (LPSTR*)psz);

	cout << result << endl;

	system("pause");
`
I was forced to use LPCSTR and cast it as I was not able to make an LPSTR array.

**Comment by ufrisk** [comment] 2022-07-10 10:14
1. are you running as elevated admin (it's required to load the pmem driver).
2. \w isn't a valid character. also there is no option called printf, it should be -printf. A more valid command line would be: `` LPCSTR psz[4] = { "", "-printf", "-device", "pmem://C:\\winpmem_x64.sys" };`

**Comment by zpacedesu** [comment] 2022-07-10 22:53
Thank you for that, I now get these messages. Does this mean it is loaded and working?

DEVICE: ERROR: Unable to communicate with winpmem driver.
[PDB]      Functionality may be limited. Extended debug information disabled
[PDB]      Offline symbols unavailable - file 'info.db' not found
[PDB]      Reason: Could not load PDB required files - symsrv.dll/dbghelp.dll.

Initialized 64-bit Windows 10.0.19041

----

And my bool result is true, I was just asking because of the Unable to communicate with driver message.

**Comment by ufrisk** [comment] 2022-07-10 23:11
Thanks for the update. It's just a bad error message that will be removed in the next version. Please disregard it for now.

Since the issue is resolved I'm closing the issue. It might be good to add the missing dll files in the error message for better quality results. I wish you the best with your memory analysis.

**Closed by ufrisk** 2022-07-10 23:11 UTC
